#! /usr/bin/env Rscript

## File description -------------------------------------------------------------
## Functions that simplify plotting for the different NMF experiments. This is
## separated from nmf_{exper}.R files because we want to use the same code for
## both NMF and zero-inflated NMF.
##
## author: kriss1@stanford.edu

## ---- libraries ----
library("plyr")
library("dplyr")
library("reshape2")
library("ggplot2")
library("ggscaffold")
library("jsonlite")

## ---- plot-utils ---
#' Plot Contours and Associated Coordinate
#'
#' This is a wrapper of ggcontours in the ggscaffold package that shows the
#' coordinate associated with point clouds.
#'
#' @param plot_data [data.frame] The data frame that contains the sampled
#'   coordinates for the contours, along with the true positions (which will be
#'   indicated with text).
#' @param plot_opts [list] A list specifying plotting appearance. Pretty much
#'   the same as the usual ggcontours plot_opts, except an extra option for plot
#'   limits.
scores_contours <- function(plot_data, plot_opts) {
  p1 <- ggcontours(plot_data, plot_opts) +
    geom_text(
      data = plot_data %>%
        group_by_(plot_opts$group) %>%
        summarise(mean_1 = mean(value_1), mean_2 = mean(value_2)),
      aes_string(x = "mean_1", y = "mean_2", label = plot_opts$group),
      col = plot_opts$mean_col,
      size = plot_opts$text_size
    ) +
    geom_text(
      data = plot_data %>% filter(iteration == 1),
      aes_string(x = "truth_1", y = "truth_2", label = plot_opts$group),
      size = plot_opts$text_size
    ) +
    scale_x_continuous(limits = plot_opts$x_lim, expand = c(0, 0)) +
    scale_y_continuous(limits = plot_opts$y_lim, expand = c(0, 0))
  p2 <- p1 +
    facet_wrap(formula(paste0("~", plot_opts$group)))
  list("grouped" = p1, "coordinates" = p2)
}

#' Reshape fitted scores for easy plotting
#'
#' Both thetas and betas in NMF are reshaped using very similar code, so we might as well combine it explicitly in one function.
#'
#' @param samples [array] The samples generated by STAN; e.g. obtained by
#'   fit${param}. Two dimensions are for the actual matrix, the third are from
#'   sampling iterations.
#' @param truth [matrix] The truth parameter values, known because we are
#'   working from a simulation.
#' @param dims [character vector] The names to use for the rows and columns of
#'   the parameter matrix.
#' @return reshaped [data.table] The melted scores, with truth along with samples.
reshape_samples <- function(samples, truth, dims) {
  reshaped <- samples %>%
    melt(varnames = c("iteration", dims)) %>%
    left_join(
      melt(
        truth,
        varnames = dims,
        value.name = "truth"
      )
    )

  reshaped[, dims[1]] <- factor(
    reshaped[, dims[1]],
    order(truth[, 1])
  )

  reshaped %>%
    setDT() %>%
    dcast(
      sprintf("%s + iteration ~ %s", dims[1], dims[2]),
      value.var = c("value", "truth")
  )
}

#' Merge Default NMF options
#'
#' @param opts [list] A partially filled list of options, to fill in with
#'   defaults.
#' @return opts [list] The version of opts with defaults filled in.
merge_nmf_opts <- function(opts = list()) {
  default_opts <- list(
    "K" = 2,
    "N" = 100,
    "P" = 75,
    "a" = 1,
    "b" = 1,
    "c" = 1,
    "d" = 1,
    "zero_inf_prob" = 0
  )
  modifyList(default_opts, opts)
}

#' Simulate NMF Data (optionally zero inflated)
#'
#' To facilitate simulation across many parameters, it's useful to have a single
#' function to generate all the quantities of interest.
#'
#' @param opts [list] A list containing parameters for simulation. Any options
#'   that are not specified will be filled in with defaults, according to
#'   merge_nmf_defaults().
#' @return A list with the latent thetas, betas, mask, and observed Y.
nmf_sim <- function(opts) {
  opts <- merge_nmf_opts(opts)
  attach(opts, warn.conflicts = FALSE)

  ## scores
  theta <- matrix(
    rgamma(N * K, rate = a, shape = b),
    N, K
  )

  ## factors
  beta <- matrix(
    rgamma(P * K, rate = c, shape = d),
    P, K
  )

  ## observations
  y <- matrix(
    rpois(N * P, theta %*% t(beta)),
    N, P
  )

  ## set some proportion to zero
  mask <- matrix(
    sample(
      c(0, 1),
      N * P,
      replace = T,
      prob = c(zero_inf_prob, 1 - zero_inf_prob)),
    N, P
  )
  y[mask == 1] <- 0

  list(
    "theta" = theta,
    "beta" = beta,
    "mask" = mask,
    "y" = y
  )
}

#' Write experiment configurations files
#'
#' This generates the JSON file on which all the experiments will be based. It
#' just creates a JSON will the full factorial combinations of input options.
#'
#' @param factors [list] A list of one-dimensional factors on which we compute
#'   the full cross-product.
#' @param path [string] The path to which to save the configurations JSON.
#' @return NULL
#' @side-effects Writes the configurations JSON to path.
factors <- list(
  "N" = c(50, 100, 200),
  "P" = c(75, 125),
  "zero_inf_prob" = c(0, 0.2, 0.5, 0.8),
  "inference" = c("gibbs", "vb"),
  "method" = c("zinf_nmf", "nmf")
)
write_configs <- function(factors, path = "config.json") {
  config_df <- expand.grid(factors) 
  config_df$id <- seq_len(nrow(config_df))
  toJSON(config_df) 

}
